name: game-dev-glory
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
ingress:
  rules:
    - component:
        name: web
      match:
        path:
          prefix: /
services:
  - name: web
    environment_slug: node-js
    github:
      repo: plotteldev/game-dev-glory
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: npm run build
    run_command: npm run start
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
    envs:
      - key: POSTMARK_SERVER_TOKEN
        value: set-in-digitalocean
        scope: RUN_TIME
        type: SECRET
      - key: POSTMARK_MESSAGE_STREAM
        value: outbound
        scope: RUN_TIME
        type: GENERAL
      - key: BOOKING_TO_EMAIL
        value: info@gamedevglory.com
        scope: RUN_TIME
        type: GENERAL
      - key: BOOKING_FROM_EMAIL
        value: Game Dev Glory <bookings@gamedevglory.com>
        scope: RUN_TIME
        type: GENERAL
